package ma.dentalTech.entities.enums;

public enum CategorieAntecedent {
    ALLERGIE,
    MALADIE_CHRONIQUE,
    CONTRE_INDICATION,
    TRAITEMENT_EN_COURS,
    ANTECEDENT_CHIRURGICAL,
    ANTECEDENT_INFECTIEUX,
    ANTECEDENT_DENTAIRE,
    HABITUDE_DE_VIE,
    AUTRE
}
